[path]
spans_raw_path=operational/operational_lifetimes_raw.csv
spans_path=operational/operational_lifetimes.csv
raw_file_path=bgp_dataset_raw/
collector_list_path=config/collector_list.txt

[mode]
extend=False

[constant]
fill=30
vis_th=1
#date_{ribs|updates}_{origin|transit}.csv.gz
raw_file_template={}_{}_{}.csv.gz

